name: "Grouparoo Cloud"
description: "Pushes Configuration to Grouparoo Cloud to validate or apply"

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  project_id:
    description: "Grouparoo Cloud Project ID"
    required: true
  token:
    description: "Grouparoo Cloud API Token"
    required: true
  type: 
    description: "Should the action run `ci` or `deploy`?"
    default: "ci"
  api_url:
    description: "Override the base URL for the Grouparoo Cloud API"
    default: "https://cloud.grouparoo.com"
    required: false

runs:
  using: "composite"
  steps:
      - run: npm ci
        shell: bash
      - shell: bash
        run: |
          if   [[ '${{ github.event_name }}' == 'push' ]]; then
            echo "COMMIT_SUBJECT=$(git log --format=%s -n 1 ${{ github.sha }})" >> $GITHUB_ENV
            echo "CONFIG_URL=${{ github.event.head_commit.url }}" >> $GITHUB_ENV
          elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            echo "CONFIG_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          fi
      - run: npx grouparoo ${{ inputs.type }} -p ${{ inputs.project_id }} -m "$CONFIG_MESSAGE" -u $CONFIG_URL
        shell: bash
        env: 
          GROUPAROO_CLOUD_API_URL: ${{ inputs.api_url }}
          GROUPAROO_CLOUD_API_TOKEN: ${{ inputs.token }}
          CONFIG_MESSAGE: ${{ env.COMMIT_SUBJECT || github.event.pull_request.title }}
          DATABASE_URL: sqlite://memory
          REDIS_URL: redis://mock
